[package]
name = "infiltrator"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "=0.5.0-rc.3"
base64 = "0.21.4"
fs_extra = "1.3.0"
byte-unit = "4.0.19"

[dependencies.uuid]
version = "1.5.0"
features = ["v4"]