[default]
address = "0.0.0.0"
port = 8000
log_level = "normal"
ident = false
part_size_bytes = 8000000

[debug]
address = "127.0.0.1"
port = 8000
log_level = "normal"
part_size_bytes = 8000000

[release]
address = "0.0.0.0"
port = 443
log_level = "critical"
ident = false
part_size_bytes = 8000000